### ISSUE TITLE
Bouton "Archiver"

### ISSUE THREAD

**Issue by entinio** [seb1k/Elastic2022#1]
Merci pour ce thème. Largement mieux que la version de base.

Cependant, le bouton "archiver" n'apparait pas lorsque l'on active ce dossier pour pouvoir archiver un email reçu. Sûrement un bout de code à replacer.

Bon courage !

**Comment by seb1k** [comment]
Merci pour ton retour, t'es le premier ;)

Pour essayer  de débloquer ca,  peux tu  m’envoyer une capture d’écran de ton bouton archive "qui marche" ( je n'utilise pas cette fonction, donc rien ne s'affiche chez moi)


Merci !

**Comment by entinio** [comment]
Voici la différence : https://i.imgur.com/CVncTkv.png

La version d'origine contient bien le bouton "Archiver" (qui permet d'archiver un email plutôt que de le supprimer quand un répertoire d'archive est configuré)

**Comment by seb1k** [comment]
Merci, ca sera corrigé la semaine prochaine, avec un autre fonctionnalité !

**Comment by seb1k** [comment]
C'est bon, merci de tester.
