### ISSUE TITLE
Small graphic glitches

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#10]
Emails do not fit the window size properly (at least for both Safari and Firefox on MacOS). This is possible to scroll horizontally for no reason. The most annoying side effect is the "more" button being partially or completely hidden as it stick to the right edge of the email content instead of the menu bar itself. Note that zooming out is not helping.

Here are a few examples:

![image](https://github.com/user-attachments/assets/343965b7-8ee7-4e62-8cc6-2165759494ea)

![image](https://github.com/user-attachments/assets/9d85bc9a-76a0-4d4a-b59e-0e78108df9a2)

**Comment by seb1k** [comment]
Multiple CSS glitch fixed (especially on safari).
Thanks to try !

(update ui.min.js & styles.min.css)

**Comment by duburcqa** [comment]
Wow that's great ! You fixed both of the issues, thanks a lot !

Since we are here, I think there are two other visual design "choices" that are detrimental to the user experience.

First, when there are many people in copy of an email, all the button are moved far away of the right, and I need to scroll horizontally to access them. I think it would make more sense to wrap the recipients on multiple lines:

![image](https://github.com/user-attachments/assets/ddbdfa72-ebb2-4589-b0d0-c25aab7a898e)

Second, I need to scroll horizontally on plain text email. It would be much better if the lines could wrap automatically to the window width:

![image](https://github.com/user-attachments/assets/e65fb3f0-7b2b-4926-bbfd-5abeb4edf8ee)

Finally, when scrolling the side bar on mobile phone, it is not possible to reach the bottom pane "mail, contact, calendar" when first touching the screen on items from the top pane "Inbox, Draft, Sent...". The scrolling is restricted to the inner top pane. You must start scrolling from the bottom of the top pane where there is no item, which is quite confusing.

**Comment by seb1k** [comment]
For the first 2 issues, thanks to try fix 
[styles.min.css.zip](https://github.com/user-attachments/files/16992042/styles.min.css.zip)

I can't reproduce the scrolling issue on my devices, can you send me a screen/video ?

Thanks.

**Comment by duburcqa** [comment]
Hum... I don't see any difference.

**Comment by duburcqa** [comment]
It works as expected. Thank you so much again ! May be a small remark but it is not a big deal. The text is split in the little of the words when wrapping lines of plain text emails. Would it be possible to move the whole world to the next line or use hyphenation instead ? If not, it is already great.

For the scrolling video let me check.

**Comment by duburcqa** [comment]
Here it is. Unfortunately you cannot see the "pointer":

https://github.com/user-attachments/assets/0c8802b6-0062-4bc5-a22c-b44e806abd22

**Comment by seb1k** [comment]
I think I resolved the 2 previous issues.
Thanks to try it in all menus (it's possible to see bugs on others "scrolling" menu on IOS)
[files.zip](https://github.com/user-attachments/files/16993070/files.zip)

**Comment by duburcqa** [comment]
Line wrapping and scrolling are both working perfectly, thank you again ! Your responsiveness is impressive.

**Comment by duburcqa** [comment]
I was still able to trigger a few scrolling glitches on IOS but difficult to reproduce:
- after opening the left panel, then clicking on vertical "..." to open the hovering menu "Compact, Empty, ..., Manager folders", and finally closing it by clicking on the email area, the hovering window go stack on the top left corner half hidden on top of the button used to open the left panel.
- In Contact app, I cannot see any groups in the upper part of the left panel. It is just empty, without even the headline "Groups" that we have on desktop
- In Calendar app, I was able to 'scroll' the whole app instead of just the vertical timeline.

**Comment by duburcqa** [comment]
https://github.com/user-attachments/assets/0c065b33-2b04-404b-9bd2-ebc13484bc88

**Comment by duburcqa** [comment]
https://github.com/user-attachments/assets/01de6b58-f5fe-46c3-898c-b56f1d5f67dd

**Comment by seb1k** [comment]
Repo updated !

I just fix the "contact menu", the 2 others glitchs are minor/long to correct.

Don't hesitate to post more issues like this .

Bon week end !

**Comment by duburcqa** [comment]
Great ! I can confirm it is now fixed. Yes I agree the other scrolling issues are not really worth the effort :)

Bon week end !
