### ISSUE TITLE
Broken calendar invites status

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#11]
This status of calendar invites is broken. It keeps "loading" indefinitely with our skin, while it works as expected with the old Elastic skin.

Here is what I get with Elastic skin:

![image](https://github.com/user-attachments/assets/0a453c2a-ebcf-4e11-aa6d-9960bb4e2913)

Here is what I get with Elastic2022 skin:

![image](https://github.com/user-attachments/assets/946c345b-f32b-411f-acff-7322896bccfb)

There is a jQuery exception in the inspection console:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/bb2fb877-a3ec-498d-91bc-8e3b00b5c8fa">

**Comment by seb1k** [comment]
Resolved in "ui.min.js".
Thank you for reporting the issue.

**Comment by duburcqa** [comment]
Thank you, I can confirm the bug is fixed !
