### ISSUE TITLE
No contact photos ?

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#13]
We can see on your screenshot that some of your contacts have pictures (PayPal, Github, Zalando, ...). This is nice, but on my side none of my contacts of pictures, do you know why ? Am I missing some non-default plugin for this ?

**Comment by seb1k** [comment]
So far, the BIMI support (brand icon) for email is not yet supported. (I hope soon : https://github.com/roundcube/roundcubemail/pull/8860 )
To add an image, you must do it via the contact page (contact > choose your contact > Edit > "clic image" to choose one )

**Comment by seb1k** [comment]
Why plugin are you using for the "contact pattern" ?

**Comment by duburcqa** [comment]
OK I see. See I was referring to BIMI support. Hopefully it will come soon !

hum... I don't think I did anything specific, but I actually have "identicon" enabled and already supported with your theme somehow x)

![image](https://github.com/user-attachments/assets/83106d3d-bbe3-40f7-bffe-7e6ffeb95f10)
