### ISSUE TITLE
Add multi-selection action button

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#14]
It would be nice to be able to apply the same action on multiple messages after selecting them, typically "mark as read", delete, move. This would be especially useful on mobile, where moving mails is inextricable currently.

**Comment by seb1k** [comment]
Did you try the "swipe" plugin to move email on phone ?

To manage multiple emails like gmail, I thinked about it, but no time to develop it ;)

**Comment by duburcqa** [comment]
OK thank you. I was thinking about something like this plugin: https://github.com/johndoh/roundcube-contextmenu

Would it be supported with your theme ?

**Comment by seb1k** [comment]
You can try it, but it don't work a 100%, some contextmenu doesn't open, like folders.

**Comment by duburcqa** [comment]
Ok I see. I really think supporting this plugin would be a huge step forward in terms of usability and user-friendliness. Being able to use the right click for commands is kind of a standard now and users are quite puzzled when they realise it does nothing on Roundcube.

**Comment by duburcqa** [comment]
Think you a will try !

**Comment by duburcqa** [comment]
hum... maybe I did something wrong but I don't see any difference:
<img width="577" alt="image" src="https://github.com/user-attachments/assets/c989898a-44b0-469c-91d0-35ec32f5f863">

Right click still does nothing.

**Comment by duburcqa** [comment]
By the way, there is no way to get access to the "swipe option" menu on mobile with your theme :/

**Comment by duburcqa** [comment]
The "move" menu for the swipe plugin is far from ideal on iOS x)

![image](https://github.com/user-attachments/assets/687b55e7-0cd8-44c3-bbb8-1f1cd0e9f2f2)

**Comment by seb1k** [comment]
I just repair the contextmenu plugin, thanks to try it :)

the swipe plugin is not my priority (not much used : https://packagist.org/?type=roundcube-plugin )

**Comment by duburcqa** [comment]
Ah nice thank you ! It is missing a button to "mark as read". This is only "mark as unread".

This is not really helping on mobile though, since there is no button to open the contextual hovering window.

**Comment by seb1k** [comment]
Je ferme pour l'instant.

Au passage, j'ai fais pas mal de modif hier ( surtout au niveau du design des PJ).
Merci de me dire si tu rencontre des probleme.

**Comment by duburcqa** [comment]
C'est effectivement plus agréable maintenant. En revanche, je crois qu'il était possible d'importer directement à son calendrier un événement en pièce jointe (.ics) et ce n'est plus possible maintenant, ce qui est pénalisant par parfois utile.

**Comment by seb1k** [comment]
Ah en effet, je connaissais pas ... je rajouterai un bouton un peu plus tard...

**Comment by duburcqa** [comment]
Your new image preview feature for attachment images is kind of buggy at the moment:

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/63ce8b22-4475-4f20-89ae-d887507ff37c">
