### ISSUE TITLE
No way to go back when fullscreen

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#15]
Is this expected that there is no "close" button when displaying an email in fullscreen mode ? This is kind of annoying but not blocking though.

![image](https://github.com/user-attachments/assets/d6d885c2-5b40-4127-a6ca-52ddb6cc2095)

**Comment by seb1k** [comment]
Just corrected !

+ lot of differents corrections (attachement, CSS...)

Thanks to try and report issue.



PS : je m'occuperai plus tard de l'icone pour les rendez-vous.

**Comment by duburcqa** [comment]
> PS : je m'occuperai plus tard de l'icone pour les rendez-vous.

Pas de soucis pour l'icône.

Il était avant possible de choisir à quel calendrier ajouter l'évènement, ce qui n'est plus le cas avec la nouvelle approche. C'est problématique dans mon cas car je dispose de plusieurs calendriers partagés avec des personnes différentes.

Par ailleurs, certains évènements ne peuvent pas être importé (je ne sais pas pourquoi). Pour le thème "standard", cela se concrétise par l'absence de bouton "save to calendar".

![image](https://github.com/user-attachments/assets/756dff34-2219-4199-83c5-bc1eee0ede2c)

![image](https://github.com/user-attachments/assets/41964722-ab23-49e8-8b5c-061b54113f2e)

Avec la nouvelle interface que tu proposes, le bouton est disponible alors qu'il ne devrait pas l'être, ce qui conduit à une erreur à l'ajout:

![image](https://github.com/user-attachments/assets/b5ddea9c-2f98-4640-99ed-c36c70c0937e)

**Comment by seb1k** [comment]
J'ai mis à jour le code pour ajouter l'événement dans différents calendriers + icone.

J'ai pas réussi à effacer le bouton lorsque un calendrier est occupé (pas réussi à reproduire la fonctionnalité) ...

Pour info, tu utilises "recherche de calendrier" ? :
![image](https://github.com/user-attachments/assets/60f95f89-79be-4c96-973c-34577b52a2cd)



> Il était avant possible de choisir à quel calendrier ajouter l'évènement, ce qui n'est plus le cas avec la nouvelle approche. C'est problématique dans mon cas car je dispose de plusieurs calendriers partagés avec des personnes différentes.

Ya combien de temps ? j'ai rien trouvé de recent dans le code de roundcube...

**Comment by duburcqa** [comment]
> J'ai pas réussi à effacer le bouton lorsque un calendrier est occupé (pas réussi à reproduire la fonctionnalité) ...

Je ne pense pas que ce soit lié à la notion de calendrier occupé ou non. Je n'ai aucune idée de la source du problème. Je peux te transférer le mail si ça peut t'aider.

> J'ai mis à jour le code pour ajouter l'événement dans différents calendriers + icone.

Les calendriers en lecteur seul sont filtrés avec le thème Elastic, ce qui est sympa car essayé d'ajouter l'évènement à un tel calendrier échouerait systématiquement, mais ce n'est pas très grave en soit.

![image](https://github.com/user-attachments/assets/3f0b216f-4d5d-4734-8cf2-730433336ce1)

> Pour info, tu utilises "recherche de calendrier" ? :

Jamais, pourquoi ? Je trouve la fonctionnalité assez inutile, il faudrait vraiment avoir une liste considérable de calendriers pour qu'elle est un intérêt.

> Il était avant possible de choisir à quel calendrier ajouter l'évènement, ce qui n'est plus le cas avec la nouvelle approche.

Je faisais référence à la fonctionnalité que tu viens de rajouter, ie ajouter l'évènement au calendrier désiré à partir du fichier "ics". Rien de place. ça fonctionnait avec la version de ton thème Elastic2022 avant que tu retravailles l'interface des pièces jointes.

**Comment by duburcqa** [comment]
Ok après vérification, je me suis probablement trompé. En effet, la liste des calendriers n'apparaît que dans le menu interactif des événements en en-tête de mail, pas lors de l'ajout d'un événement à partir d'un fichier "ics" :

![image](https://github.com/user-attachments/assets/793560b8-b2ae-48e9-be99-556e7d98559f)

**Comment by duburcqa** [comment]
J'ai finalement compris la source du problème, il s'agit d'un évènement pour lequel aucun champ "UID" n'a été spécifié. Il est donc théoriquement invalide et ne peut pas être ajouté au calendrier.

Problème que j'aimerais voir corrigé au niveau du plugin calendar soit dit en passant, mais impossible d'ouvrir une issue car pas de repo GitHub...

**Comment by seb1k** [comment]
J'ai mis à jour pour avoir seulement les calendriers "modifiables".

Les fichiers ics peuvent etre des "réunions" ou des "événements" -> (pas de menu).

Donc obligé de faire une requête "horrible" pour aller chercher la liste de calendrier ailleurs ...(j'ai rien trouvé de mieux)

J'ai mis à jour le calendrier pour supprimer la "recherche" (inutile de mon point de vue)

**Comment by seb1k** [comment]
>... plugin calendar soit dit en passant, mais impossible d'ouvrir une issue car pas de repo GitHub...

C'est celui la je crois : https://github.com/kolab-roundcube-plugins-mirror/calendar
Par contre, ne t'attends pas a avoir une réponse rapide ...

**Comment by duburcqa** [comment]
> J'ai mis à jour pour avoir seulement les calendriers "modifiables".

Parfait ça fonctionne !

> J'ai mis à jour le calendrier pour supprimer la "recherche" (inutile de mon point de vue)

Très bien, mais on se retrouve avec un espace qui semble indésirable à la place.

![image](https://github.com/user-attachments/assets/a7d9e56d-f9a2-4de7-bfe9-ef214a0cade2)

> Les fichiers ics peuvent etre des "réunions" ou des "événements" -> (pas de menu).

Hum, ok mais en l'occurrence j'ai toujours l'option pour ajouter le fichier "ics" à mon calendrier avec ton thème mais pas avec celui d'origine. Il s'agit de ce fichier:
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//inwink//NONSGML v1.0//EN
BEGIN:VTIMEZONE
TZID:Romance Standard Time
X-LIC-LOCATION:Europe/Paris
BEGIN:STANDARD
DTSTART:20221030T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20230326T020000
RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=3
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20120315T170000Z
DTSTART;TZID=Romance Standard Time:20241010T080000
DTEND;TZID=Romance Standard Time:20241010T190000
LOCATION:Accor Arena 8 Bd de Bercy 75012 Paris France
URL:https://big.bpifrance.fr
SUMMARY:Big 2024
DESCRIPTION:RDV le 10 octobre 2024 à l'Accor Arena de Paris pour le plus grand rassemblement business d'Europe ! https://big.bpifrance.fr
X-ALT-DESC;FMTTYPE=text/html:<html><body>RDV le 10 octobre 2024 à l'Accor Arena de Paris pour le plus grand rassemblement business d'Europe !<br/><br/><a href='https://big.bpifrance.fr' target='_blank'>https://big.bpifrance.fr</a></body></html>
ORGANIZER;CN="Bpifrance Evénements":mailto:contact@evenements-bpifrance.fr
END:VEVENT
END:VCALENDAR
```

**Comment by duburcqa** [comment]
> C'est celui la je crois : https://github.com/kolab-roundcube-plugins-mirror/calendar

C'est un miroir, qui n'a pas été mis à jour depuis 3 ans. Donc je n'ai aucun espoir...

**Comment by duburcqa** [comment]
For the record, it has no place here but still, here is the patch I'm using to fix support for 'ics' files without 'UID' field. Add the following content at line 748 in `/var/www/roundcube/plugins/libcalendaring/lib/libcalendaring_vcalendar.php`:
```php
        // Automatically generate a deterministic UID for the event as a fallback if not specified
        if (empty($event['uid'])) {
            $event['uid'] = 'iCal' . md5(serialize($event));
        }
```

**Comment by duburcqa** [comment]
> Les fichiers ics peuvent etre des "réunions" ou des "événements" -> (pas de menu).

Je viens de comprendre à quoi tu faisais référence. Oui pas de menu interactif associé au plugin calendar, mais néanmoins la possibilité d'ajouter le fichier "ics" à un calendrier si il est détecté comme valide, sinon l'option n'est pas disponible. Ayant corrigé le problème de fichier invalide de mon coté avec une fallback pour l'UID, gérer ce cas particulier pour éviter de renvoyer une exception n'a plus trop d'intérêt pour moi.
