### ISSUE TITLE
Graphic Glitch

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#16]
The menu that open the menu with extra options (compress, empty, mark as read, manage folder) is moving with the folders instead of staying in place:

![image](https://github.com/user-attachments/assets/81070ef4-8720-4117-8268-85903c595b13)

This is only an issue when there is so many folders that it is necessary to scroll to reach the bottom of the list

Besides, would it be possible to fill the gap between the date picker and the list of calendar ?

![image](https://github.com/user-attachments/assets/a7d9e56d-f9a2-4de7-bfe9-ef214a0cade2)

**Comment by seb1k** [comment]
Issues corrected, thanks to try.

Btw, I did a lot of changes last week, you can expect some graphic changes...

**Comment by duburcqa** [comment]
Yes I saw your commits from last week. Honestly I did not see much difference apart from the color code x)

**Comment by duburcqa** [comment]
I can confirm the first bug I mentioned is fixed. However, the button in itself is not very convenient, because its clickable area is pretty small, and one time over two I click on the folder that is behind it instead... What about moving it a little bit to the left and adding a circle behind it ? Similar to what you did for the "write" button on mobile.

**Comment by seb1k** [comment]
Updated, the button has a larger "clickable" area.
Is the new "calendar menu" is better from your point of view ?

**Comment by duburcqa** [comment]
Hum, it is now collide with the scroll bar on the right, is it possible to move the icon a little bit on the left ?

> Is the new "calendar menu" is better from your point of view ?

You mean without the search bar ? I would say yes, although adding a thin vertical dark grey line would be better, but not a big deal:

![image](https://github.com/user-attachments/assets/f8c55154-200f-4f74-a29f-831492dbe0f8)

**Comment by seb1k** [comment]
can you send me a picture where the button collide with the scrollbar (only safari on mac I presume), i'll change it in the next update (soon).

**Comment by duburcqa** [comment]
![image](https://github.com/user-attachments/assets/c42087d5-70f9-4add-ae39-9341b7620b45)

![image](https://github.com/user-attachments/assets/5d6badbd-18a7-4d1b-b95b-2926c7d622a7)

**Comment by seb1k** [comment]
I did a change, thanks to try.

**Comment by duburcqa** [comment]
I can confirm it is fixed, thank you once again !

**Comment by seb1k** [comment]
Yes, I'm copying the Outlook design ( best email client for me ), get use to it, i'll revert if you'r still unhappy in 1 week ;)

**Comment by duburcqa** [comment]
Nope, it is your skin, so do as you please. If you like it this way then keep this design.
