### ISSUE TITLE
Buggy 'delete sender if same as "from"'

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#17]
If I understand correctly, in the specific case where the sender is the same as the recipient, some graphical elements of the layout should be different, typically the sender should be deleted. I think it is not working properly because I don't see any difference:

![image](https://github.com/user-attachments/assets/0908cae6-84a4-4cbe-b788-b5f08df451a6)

**Comment by seb1k** [comment]
In the code, this condition is for another case :
![image](https://github.com/user-attachments/assets/b7761e54-dbe9-4c20-aa37-7e32180a50bd)

So normal behavior...

**Comment by duburcqa** [comment]
Ok I see, thank you !
