### ISSUE TITLE
Open image in browser

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#18]
I think it would be nice to open images in attachment in browser without saving them locally. What do you think ?

**Comment by seb1k** [comment]
I'm not forcing the download for image, maybe you have an old version of the theme.
Can you try with the last version or an other browser ?

Thanks !

**Comment by duburcqa** [comment]
Ok I see the issue. It is related to "fake" attachment when people are using images as signature. In this case, these images appear on top as attachment, but do not open in browser when clicking on them. Also, there is no thumbnail image, just the icon "png". Strange, but probably not a big deal.

**Comment by seb1k** [comment]
I'm closing this issue, I think it's related to roundcube and not my skin.
