### ISSUE TITLE
I can't find the delete button

### ISSUE THREAD

**Issue by italorecife** [seb1k/Elastic2022#19]
![image](https://github.com/user-attachments/assets/62f773ec-ea38-484e-94fb-db50a507b7ea)
using chrome latest version

**Comment by italorecife** [comment]
![image](https://github.com/user-attachments/assets/2f20d278-60e9-4bb4-a5f0-1337daaa67a2)
the problem is where the querySelector does not find the element

**Comment by italorecife** [comment]
![image](https://github.com/user-attachments/assets/89a9a389-8ac8-4839-9008-16635b40770b)
and only shows the first thumbnail

**Comment by italorecife** [comment]
version Roundcube 1.4.10

**Comment by seb1k** [comment]
Corrected in the last version, thanks to try. (The error was due to rc v1.4)

**Comment by italorecife** [comment]
Which version of RC is compatible?

**Comment by seb1k** [comment]
Sorry for misunderstanding.
I just fix the error, you have to reinstall the skin.
I advise you to update roundcube to the last version too. (better for compatibility, security, ...)

**Comment by italorecife** [comment]
If you update to 1.6.9 it works fine. thank you for your attention
