### ISSUE TITLE
faq - how to put a bar up - to help improve it

### ISSUE THREAD

**Issue by mckaygerhard** [seb1k/Elastic2022#2]
Is there a way to place a small bar on top of the entire interface, no matter what it looks like in extwin?

Existe-t-il un moyen de placer une petite barre au-dessus de toute l'interface, peu importe à quoi elle ressemble dans extwin

i mean, i try to put it using div but of course all the hole organization will mess cos now the buttons of saving and send are outside of the screen.. 

i am trying to make it work the converse js plugin but it mess the bar.. i need to get work to property document

**Comment by seb1k** [comment]
Possible but not needed for now.
