### ISSUE TITLE
bug - in mobile with low res folders dont hide or provide way to use it

### ISSUE THREAD

**Issue by mckaygerhard** [seb1k/Elastic2022#3]
your work was great.. i dont know but.. i use the theme in RC 1.4 and i dont know if are a bugt or its a fail from me..  i cannot hide or use the folders or reach the mails part to choose ..

![image](https://user-images.githubusercontent.com/1571724/179154949-ff8bbfcc-6192-4b60-bc42-a46bfa8f4c98.png)

**Comment by seb1k** [comment]
Hi,

I tested this skin for roundcube 1.5.3 only.
For you problem it's seems to be a navigator rendering issue, try with Chrome (last version) of firefox mobile.
I'll can't help you more ....

**Comment by mckaygerhard** [comment]
> Hi,
> 
> I tested this skin for roundcube 1.5.3 only. For you problem it's seems to be a navigator rendering issue, try with Chrome (last version) of firefox mobile. I'll can't help you more ....

hi thanks for your attention.. i try touse and improve this skin.. this is the only reall alternative to the roundcube skins.. i apreciate your work and tell me how i can contribute or collaborate, i was using RC 1.4 and .1.6, but well i have plans to upgrade in any case @seb1k

**Comment by seb1k** [comment]
Hi,
I'll appreciate some help :)

I didn't plan to do any change before roundcube 1.6.

If you want to improve something there is a lot of small things to make it "really" better...
It depend on what you want to work ( JS, CSS, or file size optimization )

The easiest task for me ( but most annoying ) is to fix the CSS for light mode.

I need to fix some issue for the next version :
- Add contact button for "small screen"
- Fix File Upload probleme for "small screen"

I've a lot of other ideas to improve it, but not so much time ;)
