### ISSUE TITLE
No light mode

### ISSUE THREAD

**Issue by duburcqa** [seb1k/Elastic2022#4]
Your theme is much better than the original one, great job. Yet, it is a pity light mode is not properly supported. I don't really like dark theme for webmail client in particular, because HTML email with white background are just horrible to look at...

Do you have any plan to slightly improve the light mode to make the GUI element more visible? Currently it is barely usable (as you already mentioned in the README).

**Comment by gnanet** [comment]
Loaded the available main.zip i found out it has a light mode, i would say this issue can be closed

![Elastic2022-lightmode](https://user-images.githubusercontent.com/5572007/227382255-2f6bdab2-1a84-4b02-9d03-642c6b6890ea.png)

**Comment by duburcqa** [comment]
You can click on the button but the style has not been adjusted to look nice in this mode.

**Comment by seb1k** [comment]
Yes, as [duburcqa](https://github.com/duburcqa) said, I never worked on the "light" mode.
Working on CSS is easy but **anoying** ... if someone wants to do it ... feel free !
On this project I prefer work on for other functionalities. Not enough people are asking for the light mode.

**Comment by gnanet** [comment]
Ok, there are some minot issues cthat have to be fixed, but you made the big part already. I will have a deeeper look, and try to gix them. So if i have anything ill send a PR .

**Comment by seb1k** [comment]
Hi,
I just add the light mode today, thanks to look at it.
