### ISSUE TITLE
not an issue but (hopefully) interesting: support for ident_switch plugin

### ISSUE THREAD

**Issue by BeckeBauer** [seb1k/Elastic2022#7]
I am using the [ident_switch plugin](https://packagist.org/packages/boressoft/ident_switch) since roundcube currently supports no more than one account. The elastic skin shipped with roundcube supports this plugin

![image](https://github.com/seb1k/Elastic2022/assets/51003649/4fff2e70-9e14-445e-a9f2-f08458f516f0)

I was wondering if your skin could support it as well if the plugin is activated, maybe in the settings area as separate item or as drop-down option of the mail item:

![image](https://github.com/seb1k/Elastic2022/assets/51003649/3d1d9aee-7b8d-43f7-88d0-be76993920a3)

Maybe, this is a useful addition until roundcube supports several accounts at once natively...

**Comment by seb1k** [comment]
it's added !
Thanks to try :) ( it's just at the top of the screen for now )
